Repository openkcm/extauthz, pull requests merged in 2025-08, with the labels that each got.

#57 fix: subject parsing
  internal/extauthz/check_client_cert.go
  internal/extauthz/check_client_cert_test.go
  internal/extauthz/extauthz_test.go
Labels: bug, tests

#60 fix: readiness probe
  cmd/extauthz/main.go
  internal/config/config.go
Labels: bug

#75 feat: refactor the cliendata and the policies
  examples/config.yaml
  examples/keyId.txt
  integration/status_server_test.go
  internal/business/extauthz.go
  internal/clientdata/builder.go
  internal/clientdata/factory.go
  internal/clientdata/signing/signing.go
  internal/clientdata/signing/signing_test.go
  internal/extauthz/check.go
  internal/extauthz/check_auth_header.go
  internal/extauthz/check_auth_header_test.go
  internal/extauthz/check_client_cert.go
  internal/extauthz/check_client_cert_test.go
  internal/extauthz/check_result.go
  internal/extauthz/check_test.go
  internal/extauthz/extauthz.go
  internal/flags/flags.go
  internal/policies/cedarpolicy/check.go
  internal/policies/cedarpolicy/check_test.go
  internal/policies/cedarpolicy/data_test.go
  internal/policies/cedarpolicy/engine.go
  internal/policies/cedarpolicy/engine_test.go
  internal/policies/engine.go
  internal/policy/check.go
Labels: feature, tests, refactor

#80 chore: improve logging for better debugging
  .golangci.yaml
  internal/extauthz/check.go
  internal/extauthz/check_auth_header.go
  internal/extauthz/check_client_cert.go
  internal/extauthz/check_client_cert_test.go
Labels: tests
